// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimerParcial;

namespace PrimerParcial.Migrations
{
    [DbContext(typeof(TareasDb))]
    [Migration("20201019155618_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("PrimerParcial.Detalle", b =>
                {
                    b.Property<int>("idDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("recursoidRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tareaidTarea")
                        .HasColumnType("INTEGER");

                    b.HasKey("idDetalle");

                    b.HasIndex("recursoidRecurso");

                    b.HasIndex("tareaidTarea");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("PrimerParcial.Recurso", b =>
                {
                    b.Property<int>("idRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("usuariocodigo")
                        .HasColumnType("INTEGER");

                    b.HasKey("idRecurso");

                    b.HasIndex("usuariocodigo");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("PrimerParcial.Tarea", b =>
                {
                    b.Property<int>("idTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("responsableidRecurso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tipoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("idTarea");

                    b.HasIndex("responsableidRecurso");

                    b.HasIndex("tipoid");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("PrimerParcial.TipoTarea", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("tipoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("TipoTarea");
                });

            modelBuilder.Entity("PrimerParcial.Usuario", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("codigo");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PrimerParcial.Detalle", b =>
                {
                    b.HasOne("PrimerParcial.Recurso", "recurso")
                        .WithMany()
                        .HasForeignKey("recursoidRecurso");

                    b.HasOne("PrimerParcial.Tarea", "tarea")
                        .WithMany()
                        .HasForeignKey("tareaidTarea");
                });

            modelBuilder.Entity("PrimerParcial.Recurso", b =>
                {
                    b.HasOne("PrimerParcial.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuariocodigo");
                });

            modelBuilder.Entity("PrimerParcial.Tarea", b =>
                {
                    b.HasOne("PrimerParcial.Recurso", "responsable")
                        .WithMany()
                        .HasForeignKey("responsableidRecurso");

                    b.HasOne("PrimerParcial.TipoTarea", "tipo")
                        .WithMany()
                        .HasForeignKey("tipoid");
                });
#pragma warning restore 612, 618
        }
    }
}
